name: soloforte_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Riverpod V2 (Downgraded for stability/ChangeNotifierProvider)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  
  go_router: ^17.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  google_fonts: ^6.3.3
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  arrow_path: ^3.1.0
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  timeago: ^3.7.1
  
  # Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.7
  
  # Networking
  dio: ^5.4.0
  local_auth: ^3.0.0
  sentry_flutter: ^9.8.0
  flutter_jailbreak_detection: ^1.10.0
  device_info_plus: ^12.3.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_animate: ^4.5.2
  xml: ^6.6.1
  file_picker: ^10.3.7
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  fl_chart: ^1.1.1
  cached_network_image: ^3.4.1
  pdf: ^3.11.3
  printing: ^5.14.2
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.1
  geocoding: ^4.0.0
  flutter_slidable: ^3.1.1
  workmanager: ^0.5.2
  flutter_local_notifications: ^18.0.1
  syncfusion_flutter_pdfviewer: ^31.2.18
  mask_text_input_formatter: ^2.9.0
  table_calendar: ^3.1.2
  firebase_messaging: ^16.1.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  youtube_player_flutter: ^9.1.3
  chewie: ^1.13.0
  video_player: ^2.10.1
  shake: ^3.0.0
  url_launcher: ^6.3.2
  camera: ^0.11.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  # Riverpod V2 Generators
  riverpod_generator: ^2.4.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  mockito: ^5.4.6
  # custom_lint: ^0.8.1
  # riverpod_lint: ^2.3.10

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
